// Generates modules/huxerui.cppm and the scope prelude from the public headers.
//
// Both derive one artifact from another, which is why they are generated rather
// than written: a public name added to a header and not to the module shell is
// a name `import huxerui;` cannot see, and two hand-kept copies of a macro that
// differ by a token are an illegal redefinition for a translation unit that
// both imports the module and includes view.h.
//
//   huxerui-module-gen              rewrite both files
//   huxerui-module-gen --check      fail if either is out of date
//
// The scanning is in huxerui.rules.sources, where it is unit tested; this file
// is the file I/O and the rendering.

import std;
import huxerui.rules.sources;

namespace {

namespace sources = huxerui::rules::sources;

std::string read(const std::filesystem::path& path) {
    std::ifstream in(path, std::ios::binary);
    if (!in) {
        std::cerr << "huxerui-module-gen: cannot read " << path.string() << "\n";
        std::exit(1);
    }
    return std::string(std::istreambuf_iterator<char>(in), std::istreambuf_iterator<char>());
}

std::string render_module(const std::vector<std::string>& names) {
    std::string body;
    for (const std::string& name : names) body += "    using huxerui::" + name + ";\n";
    return
"// GENERATED by huxerui-module-gen -- do not edit by hand.\n"
"//\n"
"// The C++20 module front door for HuxerUI. `import huxerui;` and\n"
"// `#include <huxerui/huxerui.h>` describe the SAME entities: the headers are\n"
"// included in the global module fragment below, so everything they declare\n"
"// stays attached to the global module and keeps its ordinary linkage and\n"
"// mangling. The module therefore changes no ABI and needs no separate library.\n"
"//\n"
"// Regenerate with:\n"
"//\n"
"//     cd mcpp/huxerui-tools && mcpp run --bin huxerui-module-gen\n"
"//\n"
"// huxerui-build-check fails when this file is out of date.\n"
"\n"
"module;\n"
"\n"
"#include <huxerui/huxerui.h>\n"
"\n"
"export module huxerui;\n"
"\n"
"export namespace huxerui {\n" + body +
"}  // namespace huxerui\n";
}

std::string render_prelude(const std::string& macros) {
    return
"// GENERATED by huxerui-module-gen -- do not edit by hand.\n"
"//\n"
"// The scope macros, extracted verbatim from <huxerui/view.h>.\n"
"//\n"
"// A macro does not cross a module boundary, so a translation unit that writes\n"
"// `import huxerui;` sees none of these -- and they are public API: hand-written\n"
"// composables use HUXERUI_SCOPE directly. huxerui.rules puts this file's\n"
"// directory on the include path, and force-includes it for a package with no\n"
"// module units; a module unit includes it in its own global module fragment.\n"
"//\n"
"// It is GENERATED rather than written because the definitions must match\n"
"// view.h's token for token: a translation unit that both imports the module and\n"
"// includes view.h would otherwise hit an illegal macro redefinition. Nothing\n"
"// here is a second source of truth.\n"
"\n"
"#pragma once\n"
"\n" + macros + "\n";
}

bool write_if_changed(const std::filesystem::path& path, const std::string& content, bool check) {
    const bool exists = std::filesystem::exists(path);
    if (check) {
        if (!exists || read(path) != content) {
            std::cerr << path.string() << " is out of date; run huxerui-module-gen\n";
            return false;
        }
        return true;
    }
    std::filesystem::create_directories(path.parent_path());
    std::ofstream out(path, std::ios::binary);
    out << content;
    std::cout << "wrote " << path.string() << "\n";
    return true;
}

} // namespace

int main(int argc, char** argv) {
    bool check = false;
    std::filesystem::path root = std::filesystem::current_path();
    for (int i = 1; i < argc; ++i) {
        const std::string_view arg = argv[i];
        if (arg == "--check") check = true;
        else if (arg == "--root" && i + 1 < argc) root = argv[++i];
        else {
            std::cerr << "usage: huxerui-module-gen [--check] [--root <dir>]\n";
            return 2;
        }
    }
    // Run from the package directory by `mcpp run`, so walk up to the tree that
    // has the headers rather than requiring --root.
    while (!std::filesystem::exists(root / "include" / "huxerui" / "huxerui.h") &&
           root.has_parent_path() && root.parent_path() != root) {
        root = root.parent_path();
    }
    const std::filesystem::path headers = root / "include" / "huxerui";
    if (!std::filesystem::exists(headers / "huxerui.h")) {
        std::cerr << "huxerui-module-gen: no include/huxerui/huxerui.h above the working directory\n";
        return 1;
    }

    std::vector<std::string> names;
    for (const std::string& relative : sources::umbrella_includes(read(headers / "huxerui.h"))) {
        const std::filesystem::path header = headers / relative;
        if (!std::filesystem::is_regular_file(header)) continue;
        for (std::string& name : sources::public_names(read(header))) names.push_back(std::move(name));
    }
    std::ranges::sort(names);
    names.erase(std::ranges::unique(names).begin(), names.end());
    if (names.empty()) {
        std::cerr << "huxerui-module-gen: no public names found -- refusing to write\n";
        return 1;
    }

    const std::string view = read(headers / "view.h");
    std::vector<std::string> macros;
    for (std::string_view name : { "HUXERUI_SCOPE", "HUXERUI_SCOPE_BEGIN", "HUXERUI_SCOPE_END" }) {
        std::string definition = sources::macro_definition(view, name);
        if (definition.empty()) {
            std::cerr << "huxerui-module-gen: " << name << " is no longer defined in view.h\n";
            return 1;
        }
        macros.push_back(std::move(definition));
    }
    std::string macro_text;
    for (std::size_t i = 0; i < macros.size(); ++i) {
        if (i) macro_text += "\n\n";
        macro_text += macros[i];
    }

    const bool ok =
        write_if_changed(root / "modules" / "huxerui.cppm", render_module(names), check) &
        write_if_changed(root / "mcpp" / "huxerui-build-rules" / "include" / "huxerui_scope_prelude.h",
                         render_prelude(macro_text), check);
    if (!ok) return 1;
    if (check) std::cout << "module shell is up to date (" << names.size() << " exported names)\n";
    return 0;
}
