// GENERATED by scripts/gen_module_exports.py -- do not edit by hand.
//
// The scope macros, extracted verbatim from <huxerui/view.h>.
//
// A macro does not cross a module boundary, so a translation unit that writes
// `import huxerui;` sees none of these -- and they are public API: hand-written
// composables use HUXERUI_SCOPE directly. huxerui.rules force-includes this
// file for every consumer, which is what makes `import huxerui;` and
// `#include <huxerui/huxerui.h>` behave the same.
//
// It is GENERATED rather than written because the definitions must match
// view.h's token for token: a translation unit that both imports the module and
// includes view.h would otherwise hit an illegal macro redefinition. Nothing
// here is a second source of truth.

#pragma once

#define HUXERUI_SCOPE(...) return ::huxerui::Scope([=]() -> ::huxerui::View __VA_ARGS__)

#define HUXERUI_SCOPE_BEGIN \
  return ::huxerui::Scope([=]() -> ::huxerui::View {

#define HUXERUI_SCOPE_END \
  });
